DROP TABLE Transaction;
DROP TABLE Transaction_class;
DROP TABLE Account;
DROP TABLE ACCOUNT_STATE;
DROP TABLE Customer;
DROP TABLE GRADE;

DROP SEQUENCE ACCOUNT_ID_SEQ;
DROP SEQUENCE TRANSACTION_ID_SEQ;

-- 등급
CREATE TABLE GRADE (
    GRADE_ID    NUMBER  PRIMARY KEY,
    GRADE_NAME  VARCHAR(15) NOT NULL,
    GRADE_MINIMUM   NUMBER  NOT NULL,
    GRADE_MAXIMUM   NUMBER  NOT NULL,
    CHARGE   NUMBER  NOT NULL
);

INSERT INTO GRADE VALUES(1, 'Admin', -1, -1, 0);
INSERT INTO GRADE VALUES(2, 'General', 0, 1199, 1000);
INSERT INTO GRADE VALUES(3, 'Family', 1200, 1199, 500);
INSERT INTO GRADE VALUES(4, 'Royal', 2000, 3999, 300);
INSERT INTO GRADE VALUES(5, 'Honor', 4000, 6999, 100);
INSERT INTO GRADE VALUES(6, 'Prestige', 7000, 9999999999, 0);

-- 고객
CREATE TABLE Customer (
	ID	VARCHAR2(30)	PRIMARY KEY,
	password	VARCHAR2(30)	NOT NULL,
	customer_name	VARCHAR2(15)	NOT NULL,
    GRADE_ID    NUMBER  REFERENCES GRADE(GRADE_ID)	NOT NULL,
	Signup_Date	DATE	DEFAULT SYSDATE	NOT NULL,
	UPDATE_Date	DATE	DEFAULT SYSDATE	NOT NULL,
    TOTAL_BALANCE   NUMBER  DEFAULT 0   NOT NULL
);

INSERT INTO CUSTOMER VALUES('admin', 'admin', '관리자', 1, sysdate, sysdate, 0);
INSERT INTO CUSTOMER VALUES('yuda', '1234', '김유다', 6, sysdate, sysdate, 10000000000);
INSERT INTO CUSTOMER VALUES('hyun', '1224', '김유현', 6, sysdate, sysdate, 99999999999);
INSERT INTO CUSTOMER VALUES('eunt', '7777', '고은태', 6, sysdate, sysdate, 77777777777);
INSERT INTO CUSTOMER VALUES('mina', '0000', '박민아', 5, sysdate, sysdate, 50000000);
INSERT INTO CUSTOMER VALUES('aeri', '8888', '정애리', 4, sysdate, sysdate, 30000000);

CREATE TABLE ACCOUNT_STATE (
    STATE_ID    NUMBER  PRIMARY KEY,
    STATE_NAME  VARCHAR2(30)    NOT NULL
);

INSERT INTO ACCOUNT_STATE VALUES(1, '사용 가능');
INSERT INTO ACCOUNT_STATE VALUES(2, '해지');

-- 계좌
CREATE TABLE Account (
	account_id	NUMBER	PRIMARY KEY,
	ID	VARCHAR2(30)	REFERENCES  Customer(id)	NOT NULL,
    STATE_ID    NUMBER  REFERENCES  ACCOUNT_STATE(STATE_ID) NOT NULL,
	balance	NUMBER  DEFAULT 0	NOT NULL,
	open_Date	DATE	DEFAULT SYSDATE	NOT NULL,
    UPDATE_DATE DATE    DEFAULT SYSDATE NOT NULL
);

CREATE SEQUENCE ACCOUNT_ID_SEQ MINVALUE 10000 MAXVALUE 99999;

INSERT INTO ACCOUNT VALUES(ACCOUNT_ID_SEQ.NEXTVAL, 'yuda', 5000000000, sysdate);
INSERT INTO ACCOUNT VALUES(ACCOUNT_ID_SEQ.NEXTVAL, 'hyun', 33333333333, sysdate);
INSERT INTO ACCOUNT VALUES(ACCOUNT_ID_SEQ.NEXTVAL, 'eunt', 77777777777, sysdate);
INSERT INTO ACCOUNT VALUES(ACCOUNT_ID_SEQ.NEXTVAL, 'mina', 50000000, sysdate);
INSERT INTO ACCOUNT VALUES(ACCOUNT_ID_SEQ.NEXTVAL, 'hyun', 33333333333, sysdate);
INSERT INTO ACCOUNT VALUES(ACCOUNT_ID_SEQ.NEXTVAL, 'aeri', 30000000, sysdate);
INSERT INTO ACCOUNT VALUES(ACCOUNT_ID_SEQ.NEXTVAL, 'yuda', 5000000000, sysdate);
INSERT INTO ACCOUNT VALUES(ACCOUNT_ID_SEQ.NEXTVAL, 'hyun', 33333333333, sysdate);

-- 거래 구분
CREATE TABLE Transaction_class (
	transaction_class_id	NUMBER	PRIMARY KEY,
	transaction_class_name	VARCHAR2(30)	NOT NULL
);

INSERT INTO TRANSACTION_CLASS VALUES(1, '입금');
INSERT INTO TRANSACTION_CLASS VALUES(2, '출금');
INSERT INTO TRANSACTION_CLASS VALUES(3, '계좌이체');

-- 거래
CREATE TABLE Transaction (
	transaction_id	NUMBER	PRIMARY KEY,
	deposit_account_id	NUMBER	REFERENCES Account(account_id),
	withdraw_account_id	NUMBER	REFERENCES Account(account_id),
	transaction_class_id	NUMBER	REFERENCES Transaction_class(transaction_class_id)	NOT NULL,
	transaction_amount	NUMBER	NOT NULL,
	transaction_Date	DATE	DEFAULT SYSDATE	NOT NULL
);

CREATE SEQUENCE TRANSACTION_ID_SEQ MINVALUE 10000 MAXVALUE 99999;

COMMIT;